# Curated multi-synonym answer key used by Tier 2 of code/rescore.py.
# Each entry: additional acceptable synonyms / defining terms beyond the original
# single target synonym (which the rescorer always retains).
# Matching is done at stem level (Snowball), so inflectional variants are covered.
EXPANSIONS = {
 'abjure':'renounce|repudiate|forswear|disavow|give up',
 'abrogate':'repeal|revoke|annul|abolish|nullify',
 'abscond':'flee|run away|leave secretly|make off|bolt',
 'abstemious':'moderate|temperate|restrained|sparing|abstinent',
 'accretion':'accumulation|buildup|gradual increase|addition',
 'acerbic':'biting|caustic|acidic|harsh|tart|scathing',
 'acidulous':'tart|acidic|sharp|biting',
 'acquiesce':'consent|comply|accept|assent|yield|give in',
 'acrimonious':'hostile|caustic|rancorous|angry|resentful',
 'adduce':'offer|present|put forward|bring forward|evidence',
 'adumbrate':'sketch|foreshadow|hint|suggest|prefigure',
 'affable':'amiable|genial|pleasant|approachable|warm|good-natured',
 'aficionado':'enthusiast|devotee|admirer|buff|lover',
 'alacrity':'willingness|readiness|promptness|enthusiasm|cheerful readiness',
 'allay':'soothe|ease|relieve|reduce|alleviate|lessen',
 'ameliorate':'better|enhance|alleviate|make better',
 'anachronism':'out of place|wrong time|wrong period|outdated|misplaced in time|belongs to another time',
 'anathema':'abomination|detested|abhorrent|loathed|hated|banned',
 'ancillary':'auxiliary|supplementary|secondary|supporting|subordinate|additional',
 'anomie':'normlessness|breakdown|instability|alienation|lawlessness|lack of norms',
 'antediluvian':'ancient|antiquated|prehistoric|outdated|very old|before the flood',
 'antipathy':'aversion|hostility|hatred|animosity|strong dislike',
 'aplomb':'composure|confidence|poise|assurance|self-possession',
 'apocryphal':'doubtful|unverified|fabricated|dubious|untrue|questionable authenticity',
 'apotheosis':'pinnacle|epitome|culmination|deification|glorification|highest point|perfect example',
 'approbation':'approval|commendation|acceptance|sanction',
 'arabesque':'ornament|pattern|decorative|flourish|ballet position|intertwined',
 'arcanum':'mystery|hidden knowledge|esoteric|deep secret',
 'arid':'barren|parched|desert|lacking moisture',
 'asperity':'severity|roughness|sharpness|bitterness|rigor',
 'aspersion':'slander|smear|defamation|disparaging|attack|damaging remark',
 'assiduous':'diligent|persistent|attentive|industrious|showing great care',
 'attenuate':'reduce|diminish|thin|lessen|make weaker',
 'auspicious':'favorable|promising|propitious|fortunate|good omen',
 'autodidact':'self-taught|self-educated|taught himself|taught herself|teaches themselves',
 'aver':'assert|declare|affirm|claim|maintain',
 'axiomatic':'self-evident|unquestionable|taken for granted|accepted as true',
 'bacchanal':'revelry|orgy|celebration|drunken|wild party|carousal',
 'banal':'trite|commonplace|unoriginal|dull|cliche|lacking originality',
 'bellicose':'aggressive|hostile|combative|belligerent|eager to fight',
 'bifurcate':'divide|fork|branch|two parts|two branches',
 'blandishment':'coaxing|cajolery|sweet talk|enticement|persuasion',
 'bombastic':'pompous|grandiose|inflated|pretentious|overblown|high-sounding',
 'bourgeois':'middle-class|middle class|conventional|materialistic',
 'burgeon':'flourish|expand|bloom|proliferate|thrive|grow rapidly',
 'cacophony':'din|discord|racket|harsh sound|jarring|unpleasant mixture of sounds',
 'calumny':'slander|defamation|false statement|smear|libel|false accusation',
 'capricious':'unpredictable|fickle|impulsive|erratic|whimsical|sudden change',
 'castigate':'criticize|rebuke|reprimand|chastise|punish|censure',
 'cathartic':'purging|purifying|releasing|relieving|emotional release',
 'celerity':'swiftness|quickness|rapidity|haste',
 'chicanery':'deception|trickery|fraud|deceit|subterfuge|dishonest',
 'choleric':'irritable|bad-tempered|irascible|hot-tempered|easily angered',
 'circuitous':'indirect|winding|meandering|not direct|longer than necessary',
 'clandestine':'covert|hidden|surreptitious|stealthy|done in secret',
 'cogent':'convincing|compelling|persuasive|forceful|clear and logical',
 'cognoscenti':'connoisseurs|insiders|in the know|well informed|knowledgeable people',
 'colloquy':'conversation|dialogue|discussion|conference|formal talk',
 'comestible':'edible|eatable|fit to eat|food item',
 'compendious':'concise|comprehensive|succinct|compact|brief but complete',
 'complaisant':'obliging|agreeable|accommodating|compliant|willing to please',
 'concatenation':'series|linking|sequence|connection|linked together',
 'concomitant':'accompanying|associated|attendant|simultaneous|occurring together',
 'conflagration':'blaze|inferno|large fire|destructive fire',
 'confluence':'junction|convergence|merging|flowing together|coming together',
 'conjecture':'speculation|supposition|inference|hypothesis|incomplete information',
 'convivial':'sociable|festive|jovial|friendly|merry|lively',
 'corpulent':'obese|overweight|portly|stout|fleshy',
 'coruscate':'glitter|flash|gleam|shine|sparkle',
 'credulous':'naive|trusting|easily deceived|believes too readily|easily convinced',
 'cupidity':'avarice|covetousness|desire for wealth|desire for money',
 'cursory':'hasty|superficial|brief|perfunctory|not thorough|without attention to detail',
 'dearth':'scarcity|shortage|absence|paucity|insufficiency',
 'debilitate':'enfeeble|drain|sap|incapacitate|make weak',
 'decadent':'declining|self-indulgent|degenerate|corrupt|luxurious|moral decline',
 'decorous':'dignified|seemly|polite|correct|respectable|good taste',
 'deleterious':'damaging|injurious|detrimental|causing harm',
 'demagogue':'rabble-rouser|agitator|manipulator|firebrand|appeals to prejudice|appeals to emotion',
 'demarcate':'delineate|separate|define|set boundaries|distinguish|boundary',
 'demure':'modest|reserved|coy|bashful|quiet',
 'denigrate':'belittle|disparage|defame|criticize|demean|speak badly',
 'derelict':'neglected|deserted|run-down|dilapidated|negligent',
 'desiccate':'dehydrate|drain|parch|remove moisture|dried',
 'desultory':'random|haphazard|unfocused|disconnected|rambling|lacking purpose',
 'diaphanous':'sheer|translucent|delicate|gauzy|transparent|see-through',
 'diatribe':'tirade|harangue|attack|denunciation|bitter criticism',
 'dichotomy':'division|contrast|separation|opposition|two parts|two opposing',
 'didactic':'instructive|educational|preachy|moralizing|intended to teach',
 'diffident':'timid|hesitant|insecure|unassertive|reserved|lacking confidence',
 'dilatory':'delaying|procrastinating|tardy|sluggish|causing delay',
 'dilettante':'dabbler|hobbyist|superficial interest|without real commitment',
 'dirge':'lament|funeral|elegy|mournful|grief',
 'discomfit':'embarrass|disconcert|fluster|unsettle|confuse|make uneasy',
 'disparate':'distinct|dissimilar|unrelated|diverse|essentially different',
 'disquiet':'unease|anxiety|distress|agitation|uneasiness',
 'dissonance':'discord|conflict|disharmony|tension|lack of harmony|inconsistency',
 'divagate':'stray|digress|drift|ramble|deviate',
 'divest':'strip|deprive|rid|sell off|take away',
 'dogmatic':'rigid|opinionated|doctrinaire|inflexible|asserts opinions|incontrovertibly true',
 'doughty':'valiant|fearless|resolute|courageous|determined',
 'dour':'stern|gloomy|sullen|severe|humorless|unfriendly',
 'draconian':'severe|strict|cruel|excessively harsh|extreme',
 'ebullient':'enthusiastic|exuberant|bubbly|lively|high-spirited|overflowing',
 'eccentric':'unconventional|quirky|strange|peculiar|weird|unusual',
 'efface':'erase|wipe out|obliterate|eliminate|rub out|make disappear',
 'effervescent':'fizzy|lively|vivacious|sparkling|bubbling|enthusiastic',
 'effulgent':'radiant|shining|brilliant|glowing|resplendent',
 'egregious':'flagrant|outrageous|glaring|blatant|conspicuously bad',
 'eleemosynary':'philanthropic|alms|benevolent|charity|charitable giving',
 'elliptical':'ambiguous|cryptic|oval|indirect|obscure|concise|omission',
 'emend':'correct|revise|edit|amend|improve text',
 'encomium':'tribute|eulogy|accolade|commendation|glowing praise|warm praise',
 'enervate':'exhaust|drain|sap|debilitate|tire|drain of energy',
 'engender':'produce|generate|create|give rise|bring about',
 'enigmatic':'puzzling|cryptic|inscrutable|baffling|difficult to understand|mysterious',
 'ennui':'listlessness|weariness|tedium|dissatisfaction|lack of excitement',
 'ensconce':'establish|install|nestle|situate|settle comfortably|firmly',
 'entreat':'plead|implore|beseech|ask earnestly|request earnestly',
 'ephemeral':'short-lived|fleeting|transient|momentary|temporary|lasting a short time',
 'epicure':'gourmet|connoisseur|gastronome|fine food|refined taste',
 'epistolary':'letters|correspondence|in the form of letters',
 'equanimity':'composure|evenness|serenity|equilibrium|level-headed|mental calmness',
 'equivocate':'evade|dodge|ambiguous|prevaricate|waffle|avoid committing',
 'ersatz':'artificial|substitute|imitation|inferior|not genuine',
 'eschew':'shun|abstain|refrain|steer clear|deliberately avoid',
 'esoteric':'obscure|specialized|arcane|abstruse|known to few|small number of people',
 'espouse':'adopt|advocate|embrace|champion|take up',
 'ethereal':'delicate|airy|heavenly|celestial|otherworldly|intangible|too perfect for this world',
 'euphemism':'mild|polite|substitute|indirect|less offensive|less harsh|in place of',
 'evanescent':'fleeting|vanishing|transient|ephemeral|momentary|quickly fading',
 'exacerbate':'aggravate|intensify|inflame|make worse|worsen',
 'excoriate':'denounce|censure|lambaste|condemn|criticize severely',
 'exculpate':'clear|absolve|exonerate|vindicate|acquit|free from blame',
 'execrable':'terrible|abominable|dreadful|atrocious|detestable|extremely bad',
 'exegesis':'interpretation|analysis|commentary|exposition|critical explanation',
 'exigent':'pressing|demanding|critical|requiring immediate',
 'exonerate':'absolve|acquit|exculpate|vindicate|free from blame|declare innocent',
 'expatiate':'elaborate|enlarge|at length|dwell|speak in detail|write in detail',
 'expeditious':'fast|swift|efficient|prompt|speedy|with speed',
 'extant':'surviving|still in existence|remaining|still exists|not destroyed',
 'extemporaneous':'improvised|impromptu|spontaneous|unrehearsed|off the cuff|without preparation',
 'extirpate':'eradicate|root out|destroy|exterminate|eliminate|completely remove',
 'facetious':'joking|flippant|humorous|not serious|tongue-in-cheek|inappropriate humor',
 'facetiousness':'flippancy|jocularity|humor|joking|inappropriate humor',
 'facile':'easy|superficial|effortless|glib|shallow|oversimplified',
 'fastidious':'meticulous|picky|exacting|particular|fussy|attentive to detail|hard to please',
 'fatuous':'foolish|inane|stupid|senseless|vacuous|pointless',
 'fecund':'productive|fruitful|prolific|producing offspring|producing many',
 'feckless':'ineffective|irresponsible|incompetent|useless|ineffectual|lacking initiative',
 'felicitous':'apt|appropriate|well-chosen|fortunate|pleasing|well suited',
 'feral':'untamed|savage|undomesticated|wild state',
 'fervid':'passionate|ardent|fervent|zealous|burning|intensely enthusiastic',
 'florid':'ornate|flowery|elaborate|ruddy|flushed|excessively intricate',
 'flummox':'bewilder|perplex|baffle|puzzle|bemuse',
 'foible':'weakness|quirk|shortcoming|failing|idiosyncrasy|minor fault',
 'forbear':'refrain|abstain|hold back|desist|restrain|patient',
 'forfend':'avert|ward off|forbid|protect|prohibit',
 'fortuitous':'accidental|chance|fortunate|unplanned|by chance|happening by luck',
 'fractious':'irritable|quarrelsome|unruly|cranky|difficult to control',
 'frangible':'breakable|brittle|delicate|easily broken',
 'frisson':'shiver|excitement|tingle|rush|sudden thrill',
 'fulsome':'insincere|overdone|effusive|lavish|excessive flattery',
 'furtive':'secretive|stealthy|sly|covert|surreptitious|attempting to avoid notice',
 'gainsay':'contradict|dispute|oppose|refute|speak against',
 'garrulous':'chatty|loquacious|wordy|verbose|rambling|excessively talkative',
 'gesticulate':'gesture|motion|signal|use hands|arm movements|hand movements',
 'gossamer':'delicate|filmy|sheer|thin|cobweb|flimsy',
 'grandiloquent':'bombastic|lofty|pretentious|high-flown|grandiose|extravagant language',
 'gregarious':'sociable|outgoing|friendly|companionable|enjoys company',
 'hackneyed':'overused|cliche|trite|stale|banal|unoriginal|lacking significance through overuse',
 'halcyon':'calm|tranquil|golden|idyllic|serene|happy|peaceful time',
 'hapless':'unfortunate|luckless|ill-fated|wretched|having no luck',
 'harangue':'tirade|rant|lecture|diatribe|lengthy aggressive|forceful speech',
 'hedonist':'pleasure-seeker|sensualist|epicurean|indulgent|pursuit of pleasure|pleasure is the highest',
 'hegemonic':'ruling|controlling|leading|supreme|dominance',
 'hermetic':'airtight|closed|isolated|impervious|protected from outside',
 'heterodox':'unorthodox|unconventional|dissenting|heretical|contrary to accepted',
 'histrionic':'theatrical|melodramatic|exaggerated|overly dramatic',
 'hubris':'arrogance|overconfidence|conceit|self-importance|excessive pride',
 'iconoclast':'nonconformist|dissenter|radical|attacks cherished beliefs|challenges tradition|challenges established',
 'idiosyncratic':'peculiar|distinctive|individual|unique|eccentric|particular to an individual',
 'ignominious':'disgraceful|humiliating|dishonorable|embarrassing|public shame',
 'imbroglio':'entanglement|complicated situation|confusion|predicament|confused mess',
 'immolate':'sacrifice|burn|destroy by fire|offer as sacrifice',
 'immutable':'unchangeable|permanent|unalterable|constant|invariable|cannot be changed|not subject to change',
 'impassive':'expressionless|unemotional|stoic|unmoved|deadpan|showing no emotion|not showing emotion',
 'impecunious':'penniless|broke|destitute|indigent|without money|little money|no money',
 'impetuous':'impulsive|rash|reckless|spontaneous|without thought|acting quickly',
 'implacable':'relentless|unappeasable|inflexible|merciless|cannot be appeased|cannot be placated',
 'importune':'pester|plead|urge|solicit|harass|persistent requests|repeatedly ask',
 'improvident':'careless|imprudent|thriftless|shortsighted|not providing for the future',
 'impugn':'challenge|dispute|question|criticize|cast doubt|call into question',
 'inchoate':'undeveloped|rudimentary|incipient|formless|just begun|not fully formed|early stage',
 'incisive':'keen|penetrating|acute|clear|trenchant|clear thinking',
 'incongruous':'out of place|inconsistent|inappropriate|mismatched|incompatible|not in harmony|not fitting',
 'incorrigible':'uncorrectable|incurable|habitual|beyond reform|irredeemable|cannot be corrected|cannot be reformed',
 'indefatigable':'tireless|untiring|unflagging|persistent|inexhaustible|never tires',
 'indigent':'needy|impoverished|destitute|penniless|lacking necessities',
 'indolent':'idle|slothful|sluggish|inactive|avoiding activity|avoiding work',
 'indomitable':'unconquerable|invincible|unbeatable|resolute|unyielding|cannot be subdued|cannot be defeated',
 'ineffable':'inexpressible|indescribable|unspeakable|beyond words|too great for words|cannot be expressed',
 'ineluctable':'inescapable|inevitable|certain|cannot be avoided|cannot be escaped',
 'inept':'incompetent|unskilled|awkward|bungling|lacking skill',
 'inexorable':'unstoppable|inevitable|unyielding|implacable|cannot be stopped|impossible to stop',
 'ingenuous':'innocent|naive|candid|frank|artless|sincere|trusting',
 'inimical':'harmful|adverse|unfriendly|antagonistic|tending to obstruct',
 'inscrutable':'enigmatic|unreadable|impenetrable|unfathomable|impossible to understand|cannot be understood',
 'insipid':'bland|flavorless|boring|tasteless|flat|lacking flavor|lacking interest',
 'insouciant':'nonchalant|unconcerned|casual|indifferent|blithe|lack of concern',
 'intractable':'unmanageable|difficult|uncontrollable|obstinate|hard to control|hard to deal with',
 'intransigent':'uncompromising|inflexible|obstinate|unyielding|refuses to compromise|refusing to change',
 'intrepid':'fearless|bold|courageous|daring|undaunted|adventurous',
 'inure':'accustom|habituate|toughen|desensitize|become used to|make accustomed',
 'invidious':'offensive|resentment|discriminatory|unjust|odious|likely to arouse',
 'irascible':'irritable|hot-tempered|quick-tempered|testy|cranky|easily angered',
 'irrevocable':'irreversible|permanent|unchangeable|cannot be undone|cannot be reversed|cannot be changed',
 'jocular':'humorous|joking|playful|jovial|witty|fond of joking',
 'jocund':'merry|jolly|lighthearted|jovial|cheerful',
 'juxtapose':'side by side|contrast|put together|position next|place close together|next to each other',
 'lachrymose':'weepy|sad|mournful|crying|tears|inclined to weep',
 'laconic':'terse|concise|short|few words|succinct|using few words',
 'laggard':'straggler|dawdler|slow person|loiterer|falls behind|lags behind',
 'lambaste':'criticize|berate|attack|castigate|thrash|harshly',
 'languid':'listless|sluggish|weak|slow|lethargic|relaxed|lacking energy',
 'largesse':'generosity|bounty|charity|liberality|giving|generous giving',
 'lassitude':'fatigue|weariness|lethargy|exhaustion|listlessness|lack of energy',
 'latent':'dormant|concealed|potential|inactive|undeveloped|not yet developed|not yet visible|hidden',
 'laudatory':'complimentary|admiring|approving|favorable|expressing praise',
 'legerdemain':'sleight of hand|trickery|deception|magic|skillful deception',
 'licentious':'immoral|promiscuous|lewd|unrestrained|dissolute|lacking moral',
 'limpid':'transparent|lucid|crystal|pellucid|perfectly clear',
 'loquacious':'talkative|chatty|garrulous|voluble|wordy|talks a lot',
 'lugubrious':'mournful|sad|dismal|sorrowful|melancholy|excessively gloomy'
}
EXPANSIONS2 = {
 'luminous':'glowing|radiant|shining|brilliant|full of light|giving off light',
 'magnanimous':'generous|forgiving|noble|big-hearted|charitable|generous spirit',
 'malevolent':'malicious|spiteful|hostile|wicked|ill will|wishing harm',
 'malinger':'fake illness|shirk|feign sickness|avoid work|pretend to be ill|pretend to be sick|exaggerate illness',
 'malleable':'pliable|adaptable|moldable|shapeable|impressionable|easily shaped|easily influenced',
 'mendacious':'dishonest|untruthful|deceitful|false|not telling the truth',
 'mercurial':'volatile|unpredictable|fickle|erratic|temperamental|sudden changes of mood',
 'meretricious':'gaudy|showy|superficially attractive|tawdry|deceptive|falsely attractive|no real value',
 'milieu':'environment|surroundings|context|background|social circle|social setting',
 'misanthrope':'cynic|loner|recluse|hate|hatred|dislikes people|dislikes humankind|dislikes others|distrusts',
 'mordant':'caustic|sarcastic|sharp|scathing|cutting|critical wit',
 'moribund':'declining|near death|stagnant|failing|about to die|point of death',
 'munificent':'lavish|liberal|bountiful|giving|very generous',
 'myopic':'shortsighted|nearsighted|near-sighted|unimaginative|lacking foresight|narrow view',
 'nebulous':'unclear|hazy|indistinct|fuzzy|cloudy|ill-defined|not well defined',
 'nefarious':'wicked|villainous|criminal|vile|sinister|extremely bad',
 'neophyte':'novice|newcomer|rookie|amateur|new convert|new member|new to',
 'nepotism':'favoring relatives|family favoritism|bias toward family|relatives|family members|friends',
 'nihilism':'rejection of values|meaninglessness|skepticism|nothing|meaningless|rejects all',
 'noisome':'foul|offensive|disgusting|noxious|harmful|bad smell|unpleasant odor',
 'nonplussed':'bewildered|perplexed|baffled|at a loss|so surprised|unsure how to react',
 'nostrum':'remedy|quack|panacea|cure-all|ineffective medicine|questionable remedy',
 'obdurate':'unyielding|hardened|inflexible|obstinate|refuses to change|stubbornly refusing',
 'obfuscate':'obscure|muddle|cloud|make unclear|complicate|less clear|difficult to understand',
 'oblique':'indirect|angled|sloping|evasive|not straightforward|slanting',
 'obsequious':'fawning|sycophantic|submissive|flattering|groveling|excessively eager to please|excessive deference',
 'obstreperous':'unruly|boisterous|defiant|rowdy|disorderly|difficult to control',
 'obviate':'prevent|eliminate|avoid|make unnecessary|preclude|remove the need',
 'occlude':'obstruct|close|shut|stop up|block',
 'odious':'repulsive|detestable|disgusting|abhorrent|offensive|deserving hatred|extremely unpleasant',
 'officious':'meddlesome|intrusive|interfering|self-important|overbearing|asserting authority|unwanted help',
 'omniscient':'all-knowing|knows everything|knowing everything|infinite knowledge|unlimited knowledge',
 'onerous':'burdensome|oppressive|taxing|demanding|difficult|involving great effort',
 'opprobrium':'disgrace|scorn|condemnation|criticism|public disgrace|harsh criticism',
 'ossify':'rigidify|solidify|inflexible|turn to bone|become rigid|cease developing',
 'ostensible':'seeming|supposed|professed|outward|surface|stated|appearing as such|apparently true',
 'ostentatious':'flashy|pretentious|flamboyant|conspicuous|gaudy|designed to impress|vulgar display',
 'palliate':'relieve|alleviate|soothe|lessen|mitigate|make less severe',
 'pallid':'wan|ashen|colorless|white|lacking color',
 'panacea':'cure-all|remedy|universal solution|elixir|solution for all',
 'panegyric':'tribute|eulogy|encomium|laudation|public speech of praise|elaborate praise',
 'paragon':'exemplar|ideal|epitome|perfect example|paradigm|model of excellence',
 'pariah':'outcast|exile|untouchable|reject|shunned|despised',
 'parsimonious':'frugal|miserly|tight-fisted|cheap|penny-pinching|unwilling to spend',
 'partisan':'one-sided|partial|factional|supporter|prejudiced|strong supporter',
 'paucity':'lack|shortage|dearth|insufficiency|fewness|small amount|small quantity',
 'pedantic':'bookish|overly precise|nitpicking|academic|overly concerned|minor details|book learning',
 'pellucid':'transparent|limpid|lucid|crystal|translucently clear|easily understood',
 'penchant':'fondness|preference|inclination|taste|tendency|strong liking',
 'penurious':'stingy|impoverished|destitute|miserly|penniless|extremely poor',
 'percipient':'perceptive|discerning|insightful|observant|perceiving',
 'perdition':'damnation|hell|destruction|eternal punishment|spiritual ruin',
 'peremptory':'commanding|imperious|dictatorial|authoritative|no argument|no refusal|insisting on immediate',
 'perfidious':'disloyal|deceitful|traitorous|faithless|untrustworthy|betrayal',
 'perfunctory':'cursory|mechanical|routine|halfhearted|superficial|minimum effort|little interest',
 'peripatetic':'traveling|itinerant|nomadic|roving|place to place',
 'pernicious':'destructive|deadly|damaging|injurious|malignant|gradual harm|subtle harm',
 'perspicacious':'perceptive|insightful|astute|shrewd|discerning|keen judgment',
 'perspicuous':'lucid|plain|easily understood|intelligible|clearly expressed',
 'pertinacious':'persistent|tenacious|determined|obstinate|holding firmly',
 'petulant':'peevish|sulky|childish|cranky|bad-tempered|childishly irritable',
 'phlegmatic':'unemotional|placid|stolid|composed|imperturbable|not easily excited',
 'picayune':'petty|small|insignificant|minor|paltry|little value',
 'pithy':'concise|terse|succinct|to the point|forceful brevity',
 'platitudinous':'trite|cliche|banal|commonplace|unoriginal|overused statements',
 'plethora':'abundance|overabundance|surplus|too many|glut|large amount|excessive amount',
 'pliable':'bendable|supple|malleable|adaptable|easily bent|easily influenced',
 'plucky':'courageous|spirited|gutsy|bold|determined|showing courage',
 'poignant':'touching|emotional|heartbreaking|affecting|evoking sadness|deeply felt',
 'polemic':'argument|controversy|criticism|dispute|diatribe|strong verbal attack|controversial argument',
 'polemical':'controversial|argumentative|combative|disputatious|strongly critical',
 'polyglot':'multilingual|many languages|several languages|multiple languages',
 'portentous':'foreboding|threatening|momentous|warning|significant|sign of something',
 'precipitate':'hasty|rash|abrupt|rush|cause|bring about|without careful consideration',
 'precocious':'advanced|gifted|mature|ahead of age|developed early|earlier than usual',
 'predilection':'liking|fondness|partiality|inclination|penchant|established preference',
 'prevaricate':'evade|equivocate|mislead|dodge|untruthful|avoid telling the truth|speak evasively',
 'proclivity':'inclination|propensity|predisposition|leaning|natural tendency',
 'profligate':'extravagant|spendthrift|dissolute|reckless|immoral|recklessly wasteful',
 'prolix':'verbose|long-winded|lengthy|rambling|tedious|too many words',
 'propinquity':'nearness|proximity|kinship|affinity|being close',
 'propitiate':'appease|placate|pacify|conciliate|win favor|regain favor',
 'prosaic':'ordinary|commonplace|mundane|unimaginative|plain|lacking poetic beauty|matter-of-fact',
 'protean':'versatile|variable|adaptable|mutable|ever-changing|readily changing|many forms',
 'proximate':'close|nearest|immediate|adjacent|next to',
 'puerile':'immature|juvenile|infantile|silly|childishly silly',
 'pugnacious':'combative|quarrelsome|belligerent|ready to fight|eager to fight|eager to argue',
 'pulchritudinous':'gorgeous|lovely|attractive|stunning|physical beauty|physically beautiful',
 'punctilious':'meticulous|precise|scrupulous|exacting|attentive to detail|careful observance|correct behavior',
 'quandary':'dilemma|predicament|difficulty|uncertainty|perplexity|difficult situation',
 'querulous':'whiny|petulant|peevish|grumbling|fretful|habitually complaining',
 'quiescent':'inactive|dormant|quiet|at rest|latent|state of inactivity',
 'quixotic':'idealistic|impractical|romantic|dreamy|fanciful|unrealistically optimistic|noble but impractical',
 'raconteur':'storyteller|narrator|anecdotist|tells stories|telling stories|anecdotes',
 'rarefied':'elevated|exclusive|esoteric|refined|thin air|select group|elite',
 'rebarbative':'repellent|irritating|objectionable|off-putting|causing annoyance|causing aversion',
 'rebuff':'reject|snub|spurn|turn down|repel|abrupt rejection',
 'recalcitrant':'defiant|uncooperative|resistant|obstinate|unruly|resisting authority|difficult to manage',
 'recidivist':'repeat offender|habitual criminal|relapser|backslider|reoffends|relapses into crime',
 'recondite':'abstruse|esoteric|profound|little known|difficult to understand|beyond ordinary',
 'redolent':'fragrant|aromatic|smelling|evocative|reminiscent|suggestive|strong smell',
 'redoubtable':'formidable|awe-inspiring|respected|imposing|worthy of fear|worthy of respect',
 'remonstrate':'protest|object|argue|complain|expostulate|forceful protest',
 'renege':'break promise|go back on|default|withdraw|fail to keep|break an agreement|break a commitment',
 'replete':'filled|abundant|well-stocked|stuffed|abounding|fully supplied',
 'reprobate':'rogue|villain|degenerate|rascal|wicked|unprincipled|morally corrupt',
 'rescind':'revoke|repeal|annul|withdraw|reverse|take back|officially cancel',
 'resplendent':'dazzling|brilliant|radiant|splendid|glorious|shining brilliantly',
 'restive':'restless|impatient|fidgety|uneasy|agitated|unruly|difficult to control',
 'reticent':'reserved|silent|uncommunicative|restrained|withdrawn|not revealing|reluctant to speak',
 'ribald':'vulgar|crude|bawdy|coarse|indecent|obscene|coarse humor',
 'ruminate':'ponder|reflect|contemplate|mull|meditate|chew|think deeply',
 'sagacious':'shrewd|astute|insightful|discerning|judicious|sound judgment|keen mental',
 'salient':'prominent|notable|striking|conspicuous|key|most noticeable',
 'salubrious':'wholesome|beneficial|health-giving|salutary|promoting health|good for health',
 'sanguine':'optimistic|positive|confident|cheerful|upbeat|cheerfully optimistic',
 'sardonic':'cynical|scornful|sarcastic|derisive|sneering|grimly mocking',
 'sartorial':'tailoring|dress|clothes|style of dress|relating to clothing|men\'s clothing',
 'scintilla':'tiny amount|spark|hint|iota|shred|smallest trace|minute amount',
 'scintillating':'brilliant|dazzling|witty|lively|glittering|sparkling',
 'scurrilous':'insulting|slanderous|defamatory|vulgar|scandalous|making scandalous claims',
 'sedulous':'diligent|hardworking|assiduous|persistent|careful|dedicated diligence',
 'sere':'withered|arid|parched|dried',
 'serpentine':'winding|snake|sinuous|coiling|curving|twisting',
 'simulacrum':'likeness|imitation|copy|representation|semblance|superficial likeness|unsatisfactory substitute',
 'skullduggery':'trickery|deception|dishonest|underhanded|unscrupulous behavior',
 'solipsistic':'self-centered|self-absorbed|egocentric|only the self|only one\'s own mind',
 'solvent':'able to pay|financially sound|not in debt|pay debts|dissolve',
 'soporific':'sleep-inducing|drowsy|boring|hypnotic|sedative|causing sleep|inducing sleep',
 'spurious':'fake|bogus|counterfeit|invalid|not genuine|false claim',
 'stentorian':'booming|thunderous|powerful voice|deafening|very loud',
 'stolid':'impassive|unemotional|expressionless|phlegmatic|little emotion|showing little feeling',
 'strident':'shrill|grating|loud|discordant|raucous|harsh sounding',
 'stultify':'stifle|deaden|numb|make ineffective|bore|cause to lose enthusiasm|impair',
 'subjugate':'dominate|subdue|enslave|oppress|bring under control|under domination',
 'sublimate':'channel|transform|divert|convert|socially acceptable',
 'suborn':'induce|corrupt|incite|persuade unlawfully|commit perjury|unlawful act',
 'subterfuge':'deception|ruse|ploy|stratagem|dodge|deceit to achieve',
 'subversive':'seditious|undermining|revolutionary|disruptive|seeking to overthrow|undermine authority',
 'succor':'aid|assistance|relief|support|comfort|help in distress',
 'sullen':'sulky|morose|moody|brooding|resentful|bad-tempered silence',
 'supercilious':'arrogant|haughty|condescending|disdainful|superior|contemptuously superior',
 'surfeit':'overabundance|glut|surplus|too much|excessive amount',
 'sycophant':'yes-man|toady|bootlicker|fawner|brown-noser|excessive flattery|flatters to gain',
 'taciturn':'quiet|reserved|uncommunicative|reticent|of few words|saying little|speaks little',
 'talisman':'amulet|lucky object|token|fetish|magical powers|good luck|bring luck',
 'tawdry':'gaudy|showy|tacky|flashy|sleazy|cheap quality|cheap and showy',
 'temerity':'audacity|nerve|recklessness|gall|rashness|excessive boldness',
 'temporal':'worldly|secular|time|of time|relating to time|not spiritual|not eternal',
 'tendentious':'partisan|one-sided|slanted|prejudiced|promoting a viewpoint|particular cause',
 'tenebrous':'gloomy|shadowy|murky|obscure|full of darkness',
 'tenuous':'thin|flimsy|slight|fragile|insubstantial|very weak',
 'terse':'concise|curt|short|abrupt|pithy|few words',
 'timorous':'timid|nervous|apprehensive|shy|frightened|lacking courage',
 'torpid':'lethargic|inactive|dormant|listless|slow|mentally inactive',
 'trenchant':'incisive|keen|cutting|penetrating|vigorous|sharply effective',
 'truculent':'aggressive|belligerent|defiant|combative|fierce|eager to fight|quick to argue',
 'turbid':'murky|muddy|opaque|unclear|not clear|full of sediment',
 'turgid':'bloated|inflated|pompous|overblown|distended|excessively embellished',
 'ubiquitous':'everywhere|omnipresent|widespread|pervasive|universal|found everywhere|present everywhere',
 'umbrage':'resentment|annoyance|displeasure|take offense|offended|feeling of anger',
 'unctuous':'smarmy|ingratiating|slick|insincere|fawning|excessively flattering|false earnestness',
 'upbraid':'reprimand|rebuke|criticize|berate|chide|find fault',
 'urbane':'sophisticated|suave|refined|cultured|elegant|courteous|polished manner',
 'vacillate':'hesitate|fluctuate|indecisive|dither|swing|alternate between',
 'vapid':'bland|insipid|lifeless|flat|uninspiring|lacking liveliness',
 'variegated':'multicolored|varied|diverse|dappled|speckled|different colors|patches of color',
 'venal':'bribable|mercenary|dishonest|purchasable|open to bribery|corruptible',
 'veracity':'truthfulness|accuracy|honesty|correctness|conformity to truth',
 'verdant':'lush|leafy|grassy|covered with vegetation|green with',
 'verisimilitude':'lifelikeness|appearance of truth|plausibility|authenticity|appearing real|seeming true',
 'veritable':'true|genuine|actual|authentic|rightly called',
 'vernal':'springtime|fresh|of spring|relating to spring|occurring in spring',
 'verve':'vigor|enthusiasm|liveliness|spirit|vitality|great energy',
 'vex':'irritate|bother|frustrate|trouble|agitate|make annoyed',
 'vicissitude':'fluctuation|variation|ups and downs|shift|unexpected change|changes in fortune',
 'vigilant':'alert|attentive|observant|on guard|wary|careful watch|watching for danger',
 'vilify':'defame|slander|malign|disparage|smear|speak ill|abusively disparaging',
 'vindicate':'clear|exonerate|absolve|prove right|defend|free from blame|justified',
 'vindictive':'vengeful|revengeful|malicious|unforgiving|desire for revenge|seeking revenge',
 'virulent':'toxic|deadly|hostile|venomous|severe|extremely harmful|bitterly hostile',
 'viscid':'gluey|adhesive|viscous|tacky|glutinous|sticky',
 'viscous':'sticky|gluey|syrupy|gelatinous|thick consistency|semifluid',
 'vitriolic':'caustic|bitter|scathing|acidic|venomous|filled with bitter',
 'vituperative':'insulting|scathing|harsh|berating|censorious|bitter and abusive',
 'vociferous':'loud|clamorous|vehement|outspoken|shouting|expressing loudly',
 'voluble':'fluent|glib|garrulous|loquacious|talkative|speaking readily',
 'voracious':'ravenous|insatiable|greedy|gluttonous|avid|eating great amounts|great appetite',
 'wan':'ashen|pallid|sickly|weak|colorless|unnaturally pale',
 'wanton':'reckless|unprovoked|gratuitous|deliberate|immoral|unrestrained|without motive|malicious',
 'wizened':'shriveled|withered|aged|dried up|shrunken',
 'xeric':'arid|desert|drought|very dry|little moisture',
 'yokel':'hick|rustic|country person|hayseed|peasant|unsophisticated|country dweller',
 'zealous':'enthusiastic|fervent|passionate|ardent|devoted|great energy',
 'zenith':'peak|summit|highest point|apex|pinnacle|culmination',
 'zephyr':'gentle wind|light wind|west wind|soft breeze|gentle breeze',
 # ---- common-word control set ----
 'happy':'joy|glad|pleased|content|cheerful|delighted',
 'sad':'unhappy|sorrowful|down|dejected|gloomy|grief|sorrow',
 'big':'large|huge|great|sizable|considerable size',
 'small':'tiny|little|minute|petite|not large',
 'fast':'quick|rapid|swift|speedy|high speed',
 'slow':'sluggish|unhurried|gradual|leisurely|not fast|low speed',
 'hot':'warm|heated|high temperature|burning|scorching',
 'cold':'chilly|cool|frigid|low temperature|lack of warmth|lacking heat',
 'angry':'furious|mad|enraged|irate|annoyed|displeasure|wrath',
 'scared':'afraid|frightened|fearful|terrified|fear',
 'tired':'exhausted|weary|fatigued|sleepy|worn out|lack of rest|need of rest',
 'rich':'wealthy|affluent|well-off|prosperous|much money|lot of money',
 'poor':'destitute|impoverished|needy|penniless|little money|lacking money',
 'strong':'powerful|mighty|sturdy|robust|great strength|physical power',
 'weak':'feeble|frail|fragile|lacking strength|not strong',
 'clean':'tidy|spotless|neat|unsoiled|free from dirt|free of dirt|without dirt',
 'dirty':'filthy|unclean|soiled|grimy|covered in dirt|covered with dirt',
 'smart':'intelligent|clever|bright|sharp|quick-witted|intelligence',
 'quiet':'silent|hushed|noiseless|little noise|no noise|low sound|making little sound',
 'loud':'noisy|deafening|booming|high volume|much noise|great deal of sound',
 'beautiful':'gorgeous|lovely|attractive|pretty|stunning|pleasing to look|aesthetic pleasure',
 'ugly':'hideous|unattractive|unsightly|unpleasant to look|not attractive',
 'cheap':'inexpensive|low-priced|affordable|low cost|little money|low price',
 'expensive':'costly|pricey|high-priced|high cost|lot of money|high price',
 'thick':'dense|wide|broad|not thin|large distance between',
 'thin':'slim|slender|narrow|skinny|lean|not thick|small distance between',
 'heavy':'weighty|hefty|massive|weighs a lot|great weight|high weight',
 'rough':'coarse|uneven|bumpy|jagged|not smooth|irregular surface',
 'smooth':'sleek|even|flat|polished|without bumps|free of roughness|no roughness',
 'safe':'secure|protected|out of danger|free from danger|free from harm|not dangerous|without risk',
 'dangerous':'risky|hazardous|unsafe|perilous|cause harm|causing harm|likely to harm',
 'funny':'humorous|amusing|comical|hilarious|laughter|makes you laugh|causing laughter',
 'weird':'strange|odd|bizarre|unusual|peculiar|not normal',
 'dry':'parched|arid|moistureless|without moisture|lacking moisture|not wet|no water|free from moisture',
 'wet':'damp|moist|soaked|saturated|covered in liquid|covered with liquid|covered in water',
 'run':'sprint|jog|dash|race|move quickly|move fast|faster than walking',
 'walk':'stroll|amble|stride|move on foot|moving on foot|moderate pace|one foot',
 'jump':'leap|hop|spring|bound|propel|off the ground|into the air',
 'sleep':'slumber|rest|doze|nap|state of rest|unconscious|eyes closed',
 'eat':'consume|ingest|devour|swallow|take in food|put food',
 'buy':'purchase|acquire|obtain|paying|pay money|exchange for money|in exchange',
 'sell':'trade|vend|exchange|for money|in exchange|to a buyer',
 'build':'construct|erect|assemble|create|make|put together',
 'destroy':'demolish|ruin|wreck|annihilate|tear down|damage beyond|cease to exist',
 'start':'begin|commence|initiate|launch|set in motion|first part',
 'stop':'halt|cease|end|discontinue|come to an end|no longer',
 'help':'assist|aid|support|lend a hand|make easier',
 'push':'shove|press|thrust|force|apply pressure|away from|move forward',
 'pull':'drag|tug|draw|yank|haul|toward oneself|toward you',
 'win':'triumph|prevail|succeed|victory|victorious|be successful|come first|first place',
 'lose':'forfeit|fail|defeated|defeat|not win|no longer have|unable to find',
 'teach':'educate|instruct|train|tutor|impart knowledge|show how|help learn',
 'learn':'study|acquire knowledge|gain knowledge|master|come to know|acquire skill',
 'hide':'conceal|cover|obscure|stash|out of sight|keep secret|cannot be seen|from view',
 'find':'locate|discover|uncover|come across|come upon',
 'give':'provide|donate|offer|hand over|present|transfer',
 'take':'grab|seize|obtain|get|acquire|lay hold|into one\'s possession|into your possession',
 'throw':'toss|hurl|fling|pitch|launch|propel|through the air',
 'catch':'snatch|grab|capture|seize|intercept|take hold',
 'fix':'repair|mend|restore|correct|make work|working order|working condition',
 'break':'shatter|smash|fracture|snap|into pieces|damage|separate into',
 'cry':'weep|sob|shed tears|tears|wail|bawl',
 'laugh':'chuckle|giggle|chortle|guffaw|amusement|express mirth|sounds of joy',
 'ask':'inquire|question|request|query|seek an answer|seek information',
 'answer':'reply|respond|response|reaction to a question',
 'choose':'select|pick|opt|decide|make a choice|decide between',
 'shout':'yell|scream|holler|bellow|call out|speak loudly|loud voice|raise one\'s voice',
 'whisper':'murmur|mutter|speak softly|quiet voice|soft voice|low voice|under one\'s breath',
 'car':'vehicle|automobile|auto|motorcar|motor vehicle',
 'house':'residence|home|dwelling|abode|building where|place where people live|living space',
 'job':'profession|occupation|employment|work|career|position|paid position',
 'money':'currency|cash|funds|medium of exchange|legal tender|payment',
 'child':'youth|kid|minor|youngster|young person|young human|boy or girl',
 'friend':'companion|pal|buddy|comrade|person you like|bond of mutual|mutual affection',
 'enemy':'foe|adversary|opponent|rival|hostile|opposed to|against you',
 'teacher':'instructor|educator|tutor|mentor|who teaches|helps students learn',
 'student':'pupil|learner|scholar|who studies|who learns|enrolled in',
 'city':'municipality|metropolis|urban|town|large settlement|populated area',
 'road':'street|highway|route|path|thoroughfare|way for vehicles|paved way',
 'animal':'creature|beast|organism|living being|living organism|fauna',
 'ocean':'sea|large body of water|body of salt water|saltwater|marine',
 'doctor':'physician|medical practitioner|medic|practices medicine|treats illness|treats patients|medical professional',
 'law':'regulation|rule|statute|legislation|legal|binding rule|system of rules',
 'game':'match|contest|competition|sport|play|played for fun|played according to rules',
 'room':'chamber|space|enclosed area|part of a building|enclosed space|within a building',
 'idea':'concept|thought|notion|plan|mental image|in the mind|mental representation',
 'clothes':'garments|clothing|apparel|attire|garb|worn on the body|items worn|cover the body',
 'food':'nourishment|sustenance|nutriment|edible|eaten|substance consumed|provides nutrition|nutrients',
 'gift':'present|offering|donation|given|without payment|without expecting|to someone',
 'garbage':'rubbish|trash|waste|refuse|litter|discarded|thrown away|unwanted material',
 'mistake':'error|blunder|fault|slip|wrong|incorrect|inaccurate',
 'picture':'image|photo|photograph|illustration|visual representation|drawing|painting',
 'tool':'instrument|implement|device|utensil|used to perform|carry out a function|perform a task',
 'building':'structure|edifice|construction|walls and a roof|constructed|erected',
 'river':'stream|waterway|watercourse|flowing water|body of water|flows',
 'mountain':'peak|summit|elevation|elevated|high landform|rises high|raised part',
 'forest':'woodland|woods|wooded|trees|covered with trees|dense growth',
 'computer':'machine|device|electronic|processes data|processes information|performs calculations|programmable',
 'airport':'terminal|airfield|aerodrome|planes|aircraft|take off and land|air travel',
 'hospital':'infirmary|medical center|clinic|medical facility|treated|medical care|sick or injured|healthcare',
}
EXPANSIONS.update(EXPANSIONS2)
