"""
Independent realness verification of the LLM-generated rare-word list.

The 429-word stimulus set was generated by an LLM (Gemini 3.1 Pro) and frozen before any
model was evaluated. Rarity is established by wordfreq/Zipf, but wordfreq assigns
Zipf 0.0 both to genuinely rare real words and to non-words, so it cannot by
itself rule out fabrication. This script cross-checks every word against two
resources that are independent of both wordfreq and the generating model:

  - WordNet (Miller 1995), via nltk
  - the public-domain `web2` dictionary word list (english_words)

It adds four columns to wordlist_zipf_validation.csv (all 429 rows):
  in_wordnet, wordnet_gloss, in_web2, verified_real
where verified_real = (zipf > 0) OR in_wordnet OR in_web2 -- i.e. the word is
attested by at least one source independent of the generating model.
"""
import os

import nltk
import pandas as pd

nltk.download("wordnet", quiet=True)
nltk.download("omw-1.4", quiet=True)
from nltk.corpus import wordnet as wn
from english_words import get_english_words_set

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(HERE, "data", "wordlist_zipf_validation.csv")

df = pd.read_csv(TARGET)
web2 = set(w.lower() for w in get_english_words_set(["web2"], lower=True))


def check(word):
    syns = wn.synsets(word)
    return pd.Series(
        {
            "in_wordnet": len(syns) > 0,
            "wordnet_gloss": syns[0].definition() if syns else "",
            "in_web2": word.lower() in web2,
        }
    )


df[["in_wordnet", "wordnet_gloss", "in_web2"]] = df["word"].apply(check)
df["verified_real"] = (df["zipf"] > 0) | df["in_wordnet"] | df["in_web2"]

df.to_csv(TARGET, index=False)

n = len(df)
print(f"Words: {n}")
print(f"  zipf > 0            : {(df['zipf'] > 0).sum()}")
print(f"  in WordNet          : {df['in_wordnet'].sum()}")
print(f"  in web2 dictionary  : {df['in_web2'].sum()}")
print(f"  verified_real (any) : {df['verified_real'].sum()}")
unverified = df[~df["verified_real"]]
print(f"  NOT verified by any : {len(unverified)}")
if len(unverified):
    print(unverified[["word", "zipf"]].to_string(index=False))

# The subset most at risk of a "hallucination" objection: zero-Zipf words.
zero = df[df["zipf"] == 0.0]
print(f"\nZero-Zipf words: {len(zero)} "
      f"(in WordNet: {zero['in_wordnet'].sum()}, in web2: {zero['in_web2'].sum()})")
print(zero[["word", "in_wordnet", "in_web2"]].to_string(index=False))
